### ISSUE TITLE
bad project

### ISSUE THREAD

**Issue by alexeygritsenko** [Win10DevGuideMVA/ProjectUpgradeUtility#1]
Hi, I have after a successful conversion project is constantly this error:

> Couldn't find the required information in the lock file. Make sure you have UAP,Version=v10.0.10240/win10-anycpu mentioned in your targets.

The "Automatically check for missing packages during build in Visual Studio" was checked.
but it does not help (like packets are recovered but the error does not disappear (

**Comment by AndyCW** [comment]
Choose x86 platform. AnyCPU is not valid for a UWP app.

Sent from my Windows Phone

**Comment by alexeygritsenko** [comment]
damn sure! I did not notice)
Now everything is OK) Thank you very much for this useful script)
